### ISSUE TITLE
[T000] - Formação da Equipe

### ISSUE THREAD

**Issue by edsomjr** [StrifeOfMythologyTD/SoMTD#1]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/T000_Formacao_da_Equipe.md

**Comment by DylanGuedes** [comment]
https://github.com/StrifeOfMythologyTD/SoMTD/wiki/Forma%C3%A7%C3%A3o-da-Equipe

obs: Trocamos o nome do jogo e da organização.

**Comment by edsomjr** [comment]
Dylan,

o nome do jogo não precisar ficar junto a descrição da formação da equipe. Favor remover.

**Comment by DylanGuedes** [comment]
Feito.
