### ISSUE TITLE
[D002] Versão Final do Documento de Visão

### ISSUE THREAD

**Issue by edsomjr** [StrifeOfMythologyTD/SoMTD#10]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/D002_Versao_Final_do_Documento_de_Visao.md

**Comment by DylanGuedes** [comment]
Professor, fizemos duas versões finais do visão: uma mais simples, mas feita a mão, e outra com mais conteúdo, mas que não sabemos se podemos utilizar (por conta da licença das imagens). 
Link para o visão 1: https://www.docdroid.net/wmc2oXk/visao-somtd.pdf.html
Link para o visão 2: https://www.docdroid.net/ar2KzCY/strife-of-mythology.pdf.html

Em ambos os visões não encontramos muito espaço para trocar texto por imagens sem que ficasse "estranho", então focamos em colocar no background coisas que remetessem a mitologia.

**Comment by edsomjr** [comment]
Sugestões:
1. Corrigir as hifenizações que ficaram erradas (exemplo: pg. 2)
2. Sintetizar a primeira parte no slide 1
3. A parte do esquema de controle está completamente textual: a substitua por uma imagem de um teclado e/ou mouse, com os botões utilizados em destaque, com uma seta/linha indicando quais as ações são executadas
4. Faltaram as plataformas na seção de plataformas. Aqui duas imagens bastam: uma da plataforma (logo do PC, Windows, Linux, PS4, etc) e uma com a classificação indicativa (E, PG-13, etc).
5. No último slide, logo da equipe + e-mail é suficiente.

**Comment by jonnatas** [comment]
705ad465611228ca498706aab55248cddf98790e 

Visão passado para o latex

https://github.com/StrifeOfMythologyTD/SoMTD/blob/master/docs/vision/vision.pdf

**Comment by edsomjr** [comment]
Ficou muito bom. Eu removeria, para finalizar, as legendas das figuras e removeria um pouco mais de texto (principalmente o que repete as informações já contidas nas figuras), mas podemos fechar esta issue já com esta versão. Removi os arquivos auto-gerados pelo latex no último commit.
