### ISSUE TITLE
[D003] Versão Inicial do GDD

### ISSUE THREAD

**Issue by edsomjr** [StrifeOfMythologyTD/SoMTD#11]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/D003_Versao_Inicial_do_GDD.md

**Comment by oliveiraMarcelo** [comment]
https://github.com/StrifeOfMythologyTD/SoMTD/wiki/Game-Design-Document#3-controles-do-jogo

**Comment by edsomjr** [comment]
Marcelo,
1. faça uma revisão do texto, corrigindo eventuais erros (por exemplo, na descrição de wave diz que são "conjunto de inimigos que nascem em conjunto" e esta repetição do termo conjunto pode/deve ser evitada);
2. A parte da "História do Jogo" descreve bem a relação entre cenários, mas falta um pouco de "história" mesmo: quem são as torres? Quem são os inimigos? Porque estão guerreando? Mesmo sem muitos detalhes, aqui é o momento de passar a ideia central do mundo do jogo.
3. A parte de "Controles" está mais para descrição das regras/gameplay. Veja que é necessário descrever o mapeamento dos inputs, quais são os periféricos a serem utilizados e uma imagem com este mapeamento.

**Comment by oliveiraMarcelo** [comment]
https://github.com/StrifeOfMythologyTD/SoMTD/wiki/Game-Design-Document
