### ISSUE TITLE
[D004] GDDD - Requisitos Tecnológicos

### ISSUE THREAD

**Issue by edsomjr** [StrifeOfMythologyTD/SoMTD#12]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/D004_GDD_Requisitos_Tecnologicos.md

**Comment by oliveiraMarcelo** [comment]
https://github.com/StrifeOfMythologyTD/SoMTD/wiki/Game-Design-Document#4-requisitos-tecnol%C3%B3gicos

**Comment by edsomjr** [comment]
Esta seção deve ser mais detalhada, pois aqui o documento não é para convencer alguém nem justificar as escolhas: é um documento de suporte à construção do jogo. Por isso devem ter as ferramentas descritas com versão (e possível link para download). Também o texto não contemplou os itens 2 e 3 da descrição da tarefa.

**Comment by oliveiraMarcelo** [comment]
https://github.com/StrifeOfMythologyTD/SoMTD/wiki/Game-Design-Document#4-requisitos-tecnol%C3%B3gicos

**Comment by edsomjr** [comment]
Remova a seção Telas, que não faz parte das duas primeiras partes do GDD.
