### ISSUE TITLE
[D005] GDD - Front End

### ISSUE THREAD

**Issue by edsomjr** [StrifeOfMythologyTD/SoMTD#13]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/D005_GDD_Front_End.md

**Comment by oliveiraMarcelo** [comment]
Página 16
https://github.com/StrifeOfMythologyTD/SoMTD/blob/gdd/docs/gdd/gdd.pdf

**Comment by edsomjr** [comment]
Marcelo,

é necessário atualizar esta seção a medida que as telas foram sendo confeccionadas.
