### ISSUE TITLE
[D006] GDD - Telas

### ISSUE THREAD

**Issue by edsomjr** [StrifeOfMythologyTD/SoMTD#14]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/D006_GDD_Telas.md

**Comment by oliveiraMarcelo** [comment]
Página 16
https://github.com/StrifeOfMythologyTD/SoMTD/blob/gdd/docs/gdd/gdd.pdf

**Comment by edsomjr** [comment]
Como já fechei a outra issue do Front End, vou deixar esta em aberto para marcar que ainda devemos atualizar as imagens para as imagens do jogo (mesmo que não sejam as definitivas).

**Comment by jonnatas** [comment]
58c3d77

**Comment by jonnatas** [comment]
Imagens atualizadas 58c3d77

**Comment by DylanGuedes** [comment]
Imagens atualizadas: https://github.com/StrifeOfMythologyTD/SoMTD/commit/ec8396ee5d0921829d283d43f6cdd206c4bd8507
Todas as telas foram feitas.
