### ISSUE TITLE
[D007] Câmera e HUD

### ISSUE THREAD

**Issue by edsomjr** [StrifeOfMythologyTD/SoMTD#15]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/D007_Camera_e_HUD.md

**Comment by oliveiraMarcelo** [comment]
Página 09
https://github.com/StrifeOfMythologyTD/SoMTD/blob/gdd/docs/gdd/gdd.pdf

**Comment by edsomjr** [comment]
Aqui a mesma coisa. Mesmo que não seja a imagem definitiva do jogo, é preciso fazer uma imagem que represente os conceitos descritos no texto. Uma mesma imagem padrão em todos os lugares não traz informação alguma e ainda confunde.

Monte uma tela exemplo, mesmo simples, com o que você descreveu, e substitua nos lugares apropriados.

**Comment by jonnatas** [comment]
01facbc41a6cdc139fecd38041c195033443d567 

Professor, essa imagem do HUD ainda não esta totalmente atualizada, tem informações que não estão descritas, que o pessoal do Darcy adicionou, mais assim que ele enviarem a imagem correta eu atualizo

https://github.com/StrifeOfMythologyTD/SoMTD/blob/gdd/docs/gdd/res/gameplay.jpg
