### ISSUE TITLE
[D009] Power Ups

### ISSUE THREAD

**Issue by edsomjr** [StrifeOfMythologyTD/SoMTD#17]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/D009_Power_Ups.md

**Comment by jonnatas** [comment]
Não temos nenhum no nosso jogo, a unica mudança de estado ocorre nas torres quando elas evoluem, através do acumulo de golds sobre as mortes do inimigos da waves. não sei se é necessário um capitulo pra isso.
