### ISSUE TITLE
[D012] Economia

### ISSUE THREAD

**Issue by edsomjr** [StrifeOfMythologyTD/SoMTD#20]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/D012_Economia.md

**Comment by oliveiraMarcelo** [comment]
Página 15
https://github.com/StrifeOfMythologyTD/SoMTD/blob/gdd/docs/gdd/gdd.pdf

**Comment by edsomjr** [comment]
Nesta seção de economia é preciso detalhar como serão as trocas de Gold por torres (custo, cooldown, se houver) e também o custo das evoluções das torres, se houver.

**Comment by jonnatas** [comment]
f40062bd949721bf312c5a996502dd03925d5eaa
