### ISSUE TITLE
[D013] Personagens Principais do Mundo do Jogo

### ISSUE THREAD

**Issue by edsomjr** [StrifeOfMythologyTD/SoMTD#21]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/D013_Principais_Personagens_do_Mundo_do_Jogo.md

**Comment by oliveiraMarcelo** [comment]
Página 11
https://github.com/StrifeOfMythologyTD/SoMTD/blob/gdd/docs/gdd/gdd.pdf

**Comment by edsomjr** [comment]
Veja que na descrição da issue é preciso detalhar, para os personagens principais,
1. sua história pregressa;
2. aliados e inimigos;
3. interesses amorosos;
4. visual;
5. idade, gênero, características marcantes.

o que ainda está pendentes. Além disso, tire o glossário do início dos capítulos e coloque ele todo na íntegra, em ordem alfabética, no final do documento.

**Comment by jonnatas** [comment]
904b74d
