### ISSUE TITLE
[D014] Veículos

### ISSUE THREAD

**Issue by edsomjr** [StrifeOfMythologyTD/SoMTD#22]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/D014_Veiculos.md

**Comment by jonnatas** [comment]
Professor não temos veículos no jogo, as waves se são monstros que se movimentam em um caminho fixo, em uma velocidade fixa. Acho que este tópico não se aplica

**Comment by edsomjr** [comment]
Ok.
