### ISSUE TITLE
[D015] Progresso do Jogo

### ISSUE THREAD

**Issue by edsomjr** [StrifeOfMythologyTD/SoMTD#23]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/D015_Progresso_do_Jogo.md

**Comment by jonnatas** [comment]
Tem-se poucas variações nos niveis do jogo eb45fde8f96b48cd94935098cb9170bfd4545b96

**Comment by edsomjr** [comment]
De toda maneira, estas diferenças devem/deveriam ser detalhadas/descritas, conforme o comando da issue.
