### ISSUE TITLE
[G006] Low-Fi Sketches

### ISSUE THREAD

**Issue by edsomjr** [StrifeOfMythologyTD/SoMTD#24]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/G006_Low_Fi_Sketches.md

**Comment by jonnatas** [comment]
Professor por enquanto temos as seguintes spritesheet, somente o cyclop com animação https://github.com/StrifeOfMythologyTD/SoMTD/blob/master/game/res/units/cyclop_spritesheetR.png

temos um rascunho de uma harpia, que na verdade é um morcego sem animação. https://github.com/StrifeOfMythologyTD/SoMTD/blob/master/game/res/units/bat.png

um centauro, também sem animação 
https://github.com/StrifeOfMythologyTD/SoMTD/blob/master/game/res/units/centauro.png

e uma medusa também sem animação.
https://github.com/StrifeOfMythologyTD/SoMTD/blob/master/game/res/units/medusa.png

TORRES
temos uma torre animada
https://github.com/StrifeOfMythologyTD/SoMTD/blob/master/game/res/tower_0.png
e uma segunda torre sem animação
https://github.com/StrifeOfMythologyTD/SoMTD/blob/master/game/res/tower_2.png

DEUSES
Temos a imagem final dos Deuses, estes não entrarão no jogo, somente no painel.
https://github.com/StrifeOfMythologyTD/SoMTD/blob/master/game/res/hades_panel.png
https://github.com/StrifeOfMythologyTD/SoMTD/blob/master/game/res/poseidon_panel.png
https://github.com/StrifeOfMythologyTD/SoMTD/blob/master/game/res/zeus_panel.png
