### ISSUE TITLE
[G007] Hi-Fi Sketches

### ISSUE THREAD

**Issue by edsomjr** [StrifeOfMythologyTD/SoMTD#25]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/G007_Hi_Fi_Sketches.md

**Comment by jonnatas** [comment]
371b62e

**Comment by jonnatas** [comment]
A arte do jogo encontrase em res, separada em pastas de acordo ao seu tipo https://github.com/StrifeOfMythologyTD/SoMTD/tree/master/game/res
