### ISSUE TITLE
[G002] Conceito do Jogo

### ISSUE THREAD

**Issue by edsomjr** [StrifeOfMythologyTD/SoMTD#3]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/G002_Conceito_do_Jogo.md

**Comment by oliveiraMarcelo** [comment]
https://github.com/AgeTD/AgeTD/wiki/Conceito-do-Jogo

**Comment by edsomjr** [comment]
Marcelo, o conceito está interessante. Contudo, falta formatar melhor o texto (por exemplo, deixar um espaço em branco após as vírgulas, melhorar a pontuação, etc). Também aconselho usar o aspell para fazer a correção ortográfica em todos os textos produzidos.

Façam uma revisão nos pontos que citei para que eu possa encerrar esta issue.

**Comment by oliveiraMarcelo** [comment]
Todos os pontos citados já foram corrigidos.

**Comment by edsomjr** [comment]
Marcelo, agora está tudo ok.

**Comment by oliveiraMarcelo** [comment]
Novo link https://github.com/StrifeOfMythologyTD/SoMTD/wiki/Conceito-do-Jogo
(renomeamos o projeto e a organização)
