### ISSUE TITLE
[P007] Controles

### ISSUE THREAD

**Issue by edsomjr** [StrifeOfMythologyTD/SoMTD#30]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/P007_Controles.md

**Comment by DylanGuedes** [comment]
O ultimo commit contém os controles do jogo (como a saída utilizando ESC, construção de torres com mouse e clicks, etc).

**Comment by edsomjr** [comment]
Dylan,

não consegui posicionar/construir as torres. Qual é o processo? (Testei a versão que está na master)

**Comment by DylanGuedes** [comment]
Edson,
o processo seria de apertar B (de "buy"), clicar em uma área não-proibida do mapa, e a torre surgiria. Eu adicionei uma mudança que volta uma pequena ajuda que criamos essa semana (é informado o botão de acionar ação de construir torre, se o lugar é proibido ou não, etc).

As fórmulas para descobrir a posição isométrica não estão precisas (o que vai parecer estranho), mas já estamos tentando arrumar isso haha.
