### ISSUE TITLE
[D016] Visão Geral do Mundo do Jogo

### ISSUE THREAD

**Issue by edsomjr** [StrifeOfMythologyTD/SoMTD#36]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/D016_Visao_Geral_do_Mundo_do_Jogo.md

**Comment by jonnatas** [comment]
Professor devido ao jogo não ser muito grande essa issue se torna repetida com todos os topicos já descritos anteriormente no gdd na secção Gameplay do jogo. 04e4688
