### ISSUE TITLE
[G003] Documento de Apresentação da Equipe

### ISSUE THREAD

**Issue by edsomjr** [StrifeOfMythologyTD/SoMTD#4]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/G003_Documento_de_Apresentacao_da_Equipe.md

**Comment by jonnatas** [comment]
https://github.com/StrifeOfMythologyTD/SoMTD/wiki/Documento-de-Apresenta%C3%A7%C3%A3o-da-Equipe

**Comment by edsomjr** [comment]
Caros, favor fazer uma última revisão acertando alguns pontos isolados (por exemplo, brasília e java com iniciais minúsculas, quando deveriam ser maiúsculas) e pontuação. No mais é isso mesmo.

**Comment by DylanGuedes** [comment]
Consertamos os pontos levantados e outros que encontramos.
