### ISSUE TITLE
[G008] Músicas

### ISSUE THREAD

**Issue by edsomjr** [StrifeOfMythologyTD/SoMTD#44]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/G008_Musicas.md

**Comment by jonnatas** [comment]
Aqui encontra-se as musicas utilizadas no jogo, não há uma tela de game over, somente um efeito e nem mapa de seleção de estágios. https://github.com/StrifeOfMythologyTD/SoMTD/tree/master/game/res/sound_efects/music
