### ISSUE TITLE
[G009] Efeitos Sonoros

### ISSUE THREAD

**Issue by edsomjr** [StrifeOfMythologyTD/SoMTD#45]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/G009_Efeitos_Sonoros.md

**Comment by jonnatas** [comment]
Aqui encontra-se as musicas utilizadas no jogo, não há uma tela de game over, somente um efeito e nem mapa de seleção de estágios. https://github.com/StrifeOfMythologyTD/SoMTD/tree/master/game/res/sound_efects/music

**Comment by jonnatas** [comment]
Aqui encontra-se os efeitos utilizados no jogo https://github.com/StrifeOfMythologyTD/SoMTD/tree/master/game/res/sound_efects/
