### ISSUE TITLE
[G010] Arte Definitiva

### ISSUE THREAD

**Issue by edsomjr** [StrifeOfMythologyTD/SoMTD#46]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/G010_Arte_Definitiva.md

**Comment by jonnatas** [comment]
Professor a arte do jogo encontra-se a pasta res, separada de acordo com o seu tipo https://github.com/StrifeOfMythologyTD/SoMTD/tree/master/game/res
