### ISSUE TITLE
[P010] Textos

### ISSUE THREAD

**Issue by edsomjr** [StrifeOfMythologyTD/SoMTD#49]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/P010_Textos.md

**Comment by DylanGuedes** [comment]
O ultimo commit contém todos os textos esperados para o jogador até então. Alguns deles (como a quantidade de gold atual do jogador, o contador que diz quanto tempo falta pra próxima wave) são dinâmicos.
