### ISSUE TITLE
[G004] Cronograma

### ISSUE THREAD

**Issue by edsomjr** [StrifeOfMythologyTD/SoMTD#5]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/G004_Cronograma.md

**Comment by jonnatas** [comment]
https://www.smartapp.com/gantterforgoogledrive/index.html?fileID=0ByT_syrpP9tqTmxEUDQySzRjejg

**Comment by edsomjr** [comment]
Caros,

lembrem-se de ir atualizando/evoluindo este cronograma a medida que o projeto avança, que vocês verão a necessidade de ajustes logo em breve. Mas por hora era isso mesmo: montar uma tentativa inicial de cronograma.
