### ISSUE TITLE
[P001] Ambiente de Desenvolvimento

### ISSUE THREAD

**Issue by edsomjr** [StrifeOfMythologyTD/SoMTD#6]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/P001_Ambiente_de_Desenvolvimento.md

**Comment by DylanGuedes** [comment]
https://github.com/AgeTD/AgeTD/wiki/Ambiente-de-Desenvolvimento

**Comment by DylanGuedes** [comment]
Novo link: https://github.com/StrifeOfMythologyTD/SoMTD/wiki/Ambiente-de-Desenvolvimento
(renomeamos o projeto e a organização)
