### ISSUE TITLE
[P002] Laço Principal

### ISSUE THREAD

**Issue by edsomjr** [StrifeOfMythologyTD/SoMTD#7]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/P002_Laco_Principal.md

**Comment by DylanGuedes** [comment]
Professor, iniciamos o loop mas ficamos na dúvida se ficou faltando algo. Localmente criamos o diretório docs, mas como ele estava vazio acabou não indo pro commit.

O commit que adiciona o loop principal é esse:
https://github.com/StrifeOfMythologyTD/SoMTD/commit/918b47c6d888d241c3f9bb672398c23b8cc24d12

**Comment by edsomjr** [comment]
Dylan,

a princípio é isso mesmo. A medida que formos avançando, algumas partes do código, como o próprio laço principal, migrarão para a engine, o Makefile ficará mais elaborado e serão necessários outros diretórios.

Em relação aos diretório docs, como vocês estão utilizando a Wiki ele será desnecessário até a construção do documento de visão.
