### ISSUE TITLE
[G005] Plano de Negócio

### ISSUE THREAD

**Issue by edsomjr** [StrifeOfMythologyTD/SoMTD#8]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/G005_Plano_de_Negocio.md

**Comment by jonnatas** [comment]
https://github.com/StrifeOfMythologyTD/SoMTD/wiki/Plano-de-neg%C3%B3cio.

**Comment by edsomjr** [comment]
Jonnatas,

as informações estão muito boas, mas falta um melhor acabamento do texto (correção de pontuação, ortografia, melhor divisão em parágrafos, etc). Também tem dados numéricos usando vírgula ao invés de ponto como separador de milhar.

Passe o pente fino para fecharmos esta issue.

**Comment by jonnatas** [comment]
Professor fizemos algumas correções: 
https://github.com/StrifeOfMythologyTD/SoMTD/wiki/Plano-de-neg%C3%B3cio

**Comment by edsomjr** [comment]
Tem ainda uma coisa pequena ou outra. Corrija a segunda citação à Steam (faltou o espaço de modo que o itálico não foi habilitado) e mais para baixo está escrito Open Souce, e não Open Source. Favor faça estas correções e sigamos adiante.
