### ISSUE TITLE
[D001] Versão Inicial do Documento de Visão

### ISSUE THREAD

**Issue by edsomjr** [StrifeOfMythologyTD/SoMTD#9]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/D001_Versao_Inicial_do_Documento_de_Visao.md

**Comment by DylanGuedes** [comment]
Professor, começamos fazendo em cima de um template, o resultado está a seguir (o template é meio poster). Foge muito ou está dentro do permitido? (link: https://fga.unb.br/articles/0001/3414/cheatsheet.pdf)

Também ficamos com dúvida quanto ao "Informações de contato da equipe", seria um e-mail da organização?

**Comment by edsomjr** [comment]
Dylan,

não tem problema em usar este formato. Se uma seção não for preenchida (como, por exemplo, a descrição dos recursos tecnológicos notáveis) é melhor omiti-la do que deixar em branco.

O contato é um e-mail da equipe como um todo. Passe o corretor ortográfico no texto (sugestão: aspell) para fecharmos esta issue.

**Comment by DylanGuedes** [comment]
Retirei as seções que estavam em branco (mais por não entendermos muito bem o que deveria entrar), corrigimos os contatos e os erros de português (reescrevemos algumas coisas também).

O documento está nesse link: https://github.com/StrifeOfMythologyTD/SoMTD/blob/master/docs/somtd-visao.pdf

(foi adicionado pelo ultimo commit)

**Comment by edsomjr** [comment]
Dylan,

agora é trabalhar os aspectos gráficos para a versão final deste documento de visão.
